apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: patch-odf-console-plugin
  namespace: default
  annotations:
      policy.open-cluster-management.io/categories: CM Configuration Management
      policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
      policy.open-cluster-management.io/description: ""
      policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  remediationAction: enforce # enforce to merge patch
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: patch-odf-console-plugin
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  plugins:
                  - odf-console    
