apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: local-storage
policyDefaults:
  namespace: default
  severity: high
  remediationAction: enforce
  complianceType: musthave
policies:
  - name: local-storage-policy
    manifests:
      - path: manifests
