---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    annotations:
        policy.open-cluster-management.io/categories: CM Configuration Management
        policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        policy.open-cluster-management.io/description: ""
        policy.open-cluster-management.io/standards: NIST SP 800-53
    name: ocp-virt-policy
    namespace: default
spec:
    disabled: false
    policy-templates:
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: ocp-virt-policy
            spec:
                object-templates:
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: hco.kubevirt.io/v1beta1
                        kind: HyperConverged
                        metadata:
                            name: kubevirt-hyperconverged
                            namespace: openshift-cnv
                        spec:
                            enableCommonBootImageImport: false
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            name: openshift-cnv
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1
                        kind: OperatorGroup
                        metadata:
                            name: kubevirt-hyperconverged-group
                            namespace: openshift-cnv
                        spec:
                            targetNamespaces:
                                - openshift-cnv
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1alpha1
                        kind: Subscription
                        metadata:
                            name: hco-operatorhub
                            namespace: openshift-cnv
                        spec:
                            channel: stable
                            name: kubevirt-hyperconverged
                            source: redhat-operators
                            sourceNamespace: openshift-marketplace
                remediationAction: enforce
                severity: high
    remediationAction: enforce
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
    name: placement-ocp-virt-policy
    namespace: default
spec:
    predicates:
        - requiredClusterSelector:
            labelSelector:
                matchExpressions: []
    tolerations:
        - key: cluster.open-cluster-management.io/unavailable
          operator: Exists
        - key: cluster.open-cluster-management.io/unreachable
          operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: binding-ocp-virt-policy
    namespace: default
placementRef:
    apiGroup: cluster.open-cluster-management.io
    kind: Placement
    name: placement-ocp-virt-policy
subjects:
    - apiGroup: policy.open-cluster-management.io
      kind: Policy
      name: ocp-virt-policy
