apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm-obs-56243116-141b-428b-9629-f387e960cb37
      endpoint: ocs-storagecluster-cephobjectstore-openshift-storage.apps.ocp4.pharriso.co.uk:443
      insecure: false
      access_key: 
      secret_key: 
