---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: controlplane0.ocp4.pharriso.co.uk
    bmac.agent-install.openshift.io.agent-label.iam-special: very-special
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: ocp4
  name: controlplane0.ocp4.pharriso.co.uk
  namespace: ocp4
spec:
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+http://192.168.50.1:8000/redfish/v1/Systems/fa211b26-e5bb-4604-a011-ec287d8ed7db
    credentialsName: bmc-nodes
    disableCertificateVerification: true
  bootMACAddress: 52:54:00:c9:e9:10
  rootDeviceHints:
    deviceName: /dev/vda
  customDeploy:
    method: start_assisted_install
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: controlplane1.ocp4.pharriso.co.uk
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: ocp4
  name: controlplane1.ocp4.pharriso.co.uk
  namespace: ocp4
spec:
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+http://192.168.50.1:8000/redfish/v1/Systems/1fa24281-3a5b-483a-bb20-f5ad97b9db96
    credentialsName: bmc-nodes
    disableCertificateVerification: true
  bootMACAddress: 52:54:00:c9:e9:11
  rootDeviceHints:
    deviceName: /dev/vda
  customDeploy:
    method: start_assisted_install
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: controlplane2.ocp4.pharriso.co.uk
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: ocp4
  name: controlplane2.ocp4.pharriso.co.uk
  namespace: ocp4
spec:
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+http://192.168.50.1:8000/redfish/v1/Systems/f4f209ed-781e-4682-ac7a-edd5169cce6b
    credentialsName: bmc-nodes
    disableCertificateVerification: true
  bootMACAddress: 52:54:00:c9:e9:12
  rootDeviceHints:
    deviceName: /dev/vda
  customDeploy:
    method: start_assisted_install
  online: true
