apiVersion: v1
kind: Node
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: controlplane0
---
apiVersion: v1
kind: Node
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: controlplane1
---
apiVersion: v1
kind: Node
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: controlplane2
